Numpy >> Numerical Python.

import numpy
import numpy as np

Numpy >> Its a library of python which deals with numbers. 
         It is used to perform many different operations on array.
         
array >> A numpy array is a homogeneous data type, which means it assign one data type to each and every single element inside the array is same.
It is time efficient. 
Arrays are 50 time faster than list.

Differemnt no. of operations which we can perform on array :
- basic arithmetical operations   +-*/ //
- linear algebra
- matrix
- probability
- statistic
- Logarithmic Operations 
- Trignometric operations.
- Random number generation.

In [2]:
import numpy as np

In [3]:
list1 = [1,4,5,8]
type(list1)

list

In [4]:
print(np.__version__)

1.21.5


In [5]:
arr = np.array(list1)
arr

array([1, 4, 5, 8])

In [6]:
list2 = [1,3,5,"python"]  # heterogenous == home == string 
arr1 = np.array(list2)    # 1,3,5 == int ,"python" == str 
arr1,type(arr1)           # homegenous == str 

(array(['1', '3', '5', 'python'], dtype='<U11'), numpy.ndarray)

In [7]:
tup1 = (1,2,3,4)
array =np.array(tup1)
array,type(array)

(array([1, 2, 3, 4]), numpy.ndarray)

In [8]:
array = np.array([4,5,2,1])
array, type(array)                           #ndarray = n-dimenstional array

(array([4, 5, 2, 1]), numpy.ndarray)

In [9]:
arr1 =np.array([1,2,3,5])
arr1,type(arr1)

(array([1, 2, 3, 5]), numpy.ndarray)

## Data type of the array 

In [10]:
# We have converted a list into array
arr = np.array(list1)
arr, type(arr)

(array([1, 4, 5, 8]), numpy.ndarray)

In [11]:
arr = np.array((1,2,3,4))
arr, type(arr), arr.dtype

(array([1, 2, 3, 4]), numpy.ndarray, dtype('int32'))

In [12]:
list1 = [1,3,4,5.6]   # 
arr2 = np.array(list1)
arr2,type(arr2),arr2.dtype

(array([1. , 3. , 4. , 5.6]), numpy.ndarray, dtype('float64'))

int to float, complex, string
Float to int, complex, str
Complex to string

In [13]:
list1

[1, 3, 4, 5.6]

In [14]:
arr = np.array([1,4,3+2j])   # complex 
arr, type(arr), arr.dtype

(array([1.+0.j, 4.+0.j, 3.+2.j]), numpy.ndarray, dtype('complex128'))

In [15]:
array = np.array([1,3,2+6j,4.5,3.5])
array,type(array),array.dtype

(array([1. +0.j, 3. +0.j, 2. +6.j, 4.5+0.j, 3.5+0.j]),
 numpy.ndarray,
 dtype('complex128'))

In [16]:
array = np.array(["2",34,56,4.6,3+2j])
array,type(array),array.dtype

(array(['2', '34', '56', '4.6', '(3+2j)'], dtype='<U64'),
 numpy.ndarray,
 dtype('<U64'))

In [17]:
array = np.array([2,34,56,4.6,3+2j])
array,type(array),array.dtype

(array([ 2. +0.j, 34. +0.j, 56. +0.j,  4.6+0.j,  3. +2.j]),
 numpy.ndarray,
 dtype('complex128'))

## Assigning a data type to an array

arr.dtype ==  it is used to check the datatype of elements of array 
type(arr) == it is uswed to check the type of array 

In [18]:
arr1 = np.array([1,2,3,4])
arr1,arr1.dtype,type(arr1)

(array([1, 2, 3, 4]), dtype('int32'), numpy.ndarray)

In [19]:
array = np.array([1,4,5,7], dtype = 'int')
array, array.dtype

(array([1, 4, 5, 7]), dtype('int32'))

In [20]:
array = np.array([1,4,6,8],dtype = "complex")
array,array.dtype

(array([1.+0.j, 4.+0.j, 6.+0.j, 8.+0.j]), dtype('complex128'))

In [21]:
array = np.array([1,4,5,7], dtype = 'float')
array, array.dtype,type(array)

(array([1., 4., 5., 7.]), dtype('float64'), numpy.ndarray)

In [22]:
array = np.array([1,4,5,7], dtype = 'complex')
array, array.dtype

(array([1.+0.j, 4.+0.j, 5.+0.j, 7.+0.j]), dtype('complex128'))

In [23]:
array1 = np.array([2,4,6,8,10],dtype = "float")
array1

array([ 2.,  4.,  6.,  8., 10.])

In [24]:
array = np.array([1,4,5,7], dtype = 'str')
array, array.dtype

(array(['1', '4', '5', '7'], dtype='<U1'), dtype('<U1'))

In [25]:
array = np.array([1,4,5,7], dtype = 'object')
array, array.dtype

(array([1, 4, 5, 7], dtype=object), dtype('O'))

### ndim 
it is used to chek the dimentions of array 

In [26]:
array =np.array(4)
array,array.ndim

(array(4), 0)

In [27]:
arr = np.array([1,4,5,3])
arr, arr.ndim

(array([1, 4, 5, 3]), 1)

In [28]:
arr = np.array([[[1,4,5,3]]])
arr, arr.ndim

(array([[[1, 4, 5, 3]]]), 3)

In [29]:
arr =  np.array([[1,2],[7,5]])
arr, arr.ndim

(array([[1, 2],
        [7, 5]]),
 2)

In [30]:
arr =  np.array([[1,2,7,5,4,5]])
arr, arr.ndim

(array([[1, 2, 7, 5, 4, 5]]), 2)

In [31]:
arr =  np.array([[1,2],[7,5],[4,5]])
arr, arr.ndim

(array([[1, 2],
        [7, 5],
        [4, 5]]),
 2)

In [32]:
arr =  np.array([])
arr, arr.ndim

(array([], dtype=float64), 1)

In [33]:
arr =  np.array([[[1,2],[7,5],[4,5],[2,4]]])
arr, arr.ndim

(array([[[1, 2],
         [7, 5],
         [4, 5],
         [2, 4]]]),
 3)

In [34]:
arr =  np.array([[1,2,4,6,7],[7,5,5,7,8],[4,5,0,8,9]])
arr, arr.ndim

(array([[1, 2, 4, 6, 7],
        [7, 5, 5, 7, 8],
        [4, 5, 0, 8, 9]]),
 2)

In [35]:
arr =  np.array([[[[[1,2,7,5,4,5]]]]])
arr, arr.ndim

(array([[[[[1, 2, 7, 5, 4, 5]]]]]), 5)

In [36]:
arr =np.array([[1,2,3,5]],dtype = "float")
arr,type(arr),arr.dtype,arr.ndim

(array([[1., 2., 3., 5.]]), numpy.ndarray, dtype('float64'), 2)

## Converting the dimentions of an array   
## ndmin

We can not convert the higher dimentions into the lower dimentions. 
we can only convert lowe dimenstions into the higher                                                           (dimenstion -ndim)
array = np.array([1,4,2,5,6], ndmin = 2)
array, array.ndim

In [37]:
arr = np.array([2,4,5])
arr.ndim

1

In [38]:
arr = np.array([2,4,5],ndmin=3)
arr.ndim,arr

(3, array([[[2, 4, 5]]]))

In [39]:
arr

array([[[2, 4, 5]]])

In [40]:
arr = np.array([[[2,4,5]]],ndmin=1)
arr.ndim,arr

(3, array([[[2, 4, 5]]]))

In [41]:
array =np.array([1,3,4,5,7],ndmin =2)
array, array.ndim

(array([[1, 3, 4, 5, 7]]), 2)

In [42]:
array = np.array([1,4,2,5,6], ndmin = 5)
array, array.ndim

(array([[[[[1, 4, 2, 5, 6]]]]]), 5)

In [43]:
array = np.array([[1,4],[2,5]], ndmin = 1)
array, array.ndim

(array([[1, 4],
        [2, 5]]),
 2)

In [44]:
array = np.array([[1,4],[2,5]], ndmin = 5)
array, array.ndim  

(array([[[[[1, 4],
           [2, 5]]]]]),
 5)

## Indexing of an array

In [45]:
+ve indexing 

0  1   2    3

-ve 



SyntaxError: invalid syntax (2390851613.py, line 1)

In [ ]:
array = np.array([4,10,20,45])

array[2]

In [ ]:
array[0]

In [ ]:
array[3]

In [ ]:
array[1]

In [4]:
array = np.array([[4,10],[20,45]])
array[0]

array([ 4, 10])

In [ ]:
array[0][0]

In [ ]:
array[1][1]

In [ ]:
# [[4,10],[20,45],[2,4]]  4,10 = [0]  ,20,24 = [1] , [2,4] = [2]

In [ ]:
array[0][0]

In [ ]:
array[0][1]

In [ ]:
array[1][0]

In [ ]:
array = np.array([[4,10],[20,45],[7,8]])
array[0]

In [ ]:
20,7,10


In [ ]:
array = np.array([[[4,10,5],[20,45,41],[7,8,9]],
                  [[1,2,3],[4,5,6],[7,8,9]]])
array,array.ndim


In [ ]:
array[0][0][1]

In [ ]:
array[1]

In [ ]:
10,9,7,5,6

In [ ]:
array[0][1]

In [ ]:
array[0][1][2]

In [ ]:
array[0][0][1]

In [ ]:
array[1][1][1]

## Slicing

In [52]:
import numpy as np

In [53]:
array = np.array([7,8,9,10])
array

array([ 7,  8,  9, 10])

In [54]:
array[0:2]       # in slicing we got the n-1 indexing element 

array([7, 8])

In [55]:
array[:2]

array([7, 8])

In [56]:
array = np.array([[7,8,9,10]])
array[:,:] # all rows and all columns

array([[ 7,  8,  9, 10]])

In [57]:
array[:] # all rows and all columns

array([[ 7,  8,  9, 10]])

In [58]:
array = np.array([[1,2,3],[4,5,6]])
array[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array[:,:]   # all the rows and all the columns 

In [59]:
array[:,1:]  # all rows and 1st and 2nd column.

array([[2, 3],
       [5, 6]])

In [60]:
array[:1,1:]   # in slicing end index is excluded (n-1)

array([[2, 3]])

In [ ]:
array[:,:1]  # all rows and 0th indexing column.  

In [ ]:
array[:1,1:]   # zeroth row 1st and 2nd idexing column 

In [61]:
array = np.array([[[1,2,3],[4,5,6]],[[2,5,8],[3,6,9]]])
array

array([[[1, 2, 3],
        [4, 5, 6]],

       [[2, 5, 8],
        [3, 6, 9]]])

In [62]:
[4,5,6]
[5,8]
[6,9]
5
6

2
5
5
6


6

In [63]:
array[1:]

array([[[2, 5, 8],
        [3, 6, 9]]])

In [ ]:
array[0:1]

In [ ]:
array[1:,0:1]

In [ ]:
array[0][1:2,2:3]

In [ ]:
array[1][0:1]

In [ ]:
array

In [ ]:
array[1][:,1:3]

In [ ]:
array[1,:1,:2]

In [ ]:
array[0, :,1:2 ]

In [ ]:
array[:1, :,1:2]

In [ ]:
array = np.array([[[4,10,5],[20,45,41],[7,8,9]],
                  [[1,2,3],[4,5,6],[6,8,10]]])
array

# [20,45,41]
# [9]
# [4,5,6]
# [45]              
    
                  

In [ ]:
array[1:, :,2:]

In [ ]:
array[1:,0:2,2:]

## shape of array

In [ ]:
array = np.array([1,4,5,7])
array.ndim

In [5]:
array = np.array([1,4,5,7])
array.shape

(4,)

In [11]:
array = np.array([[1,4,5,7]])
print(array)
array.shape

[[1 4 5 7]]


(1, 4)

In [7]:
array = np.array([[1,4],[5,7]])
array
array.shape

(2, 2)

In [12]:
array = np.array([[1,4,6],[5,7,5]])
print(array)
array.shape

[[1 4 6]
 [5 7 5]]


(2, 3)

In [13]:
array = np.array([[[1,4,4],[5,7,5]],[[4,5,6],[7,8,9]]])
print(array)
array.shape # no. of elements, no. of rows, no. of columns

[[[1 4 4]
  [5 7 5]]

 [[4 5 6]
  [7 8 9]]]


(2, 2, 3)

In [ ]:
array = np.array([[1,4,4],[5,7,8]])
print(array)
array.shape

In [ ]:
#1) 3,3,4
#2) 2,3,4


## Reshape

In [ ]:
array1 = np.array([1,2,4,5,7,8],ndmin=4)
array1,array1.shape


In [ ]:
1*1*1*6 = 6
6*1 =6 
2*3
3*2
1*2*3
1*6

In [ ]:
array = array1.reshape(6,1)
array

In [ ]:
array = array.reshape(2,3)
array

In [ ]:
array = array.reshape(1,6)
array

In [46]:
array = array.reshape(1,2,3,1)
array

ValueError: cannot reshape array of size 4 into shape (1,2,3,1)

In [47]:
array = array.reshape(1,2,3)
array

ValueError: cannot reshape array of size 4 into shape (1,2,3)

In [51]:
three=np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
#print(three.ndim)
three.reshape((2, 3, 2))

array([[[1, 2],
        [3, 1],
        [2, 3]],

       [[1, 2],
        [3, 1],
        [2, 3]]])