In [1]:
import numpy as np

In [ ]:
shape 
reshape == 
array to list == tolist
list to array 

In [ ]:
array = np.array([1,2,3,4,5,6])  # 1d  # shape [6]
array, print(type(array)),array.shape,array.ndim

# converting an array into list.

In [ ]:
array,type(array)

In [ ]:
list1 = array.tolist() # converting an array into list.
list1, type(list1)

In [ ]:
list1 = [24,78,45,4]
array = np.array(list1)
array,type(array)

## creating an empty array

In [ ]:
array =np.array([])
array

In [ ]:
shape 
reshape
converting array in to list
list to array 
empty array 

## Functions

## 1. zeros()

It will create an array where all the elements will be zero

In [2]:
array = np.zeros(3)
array,array.dtype,type(array)

(array([0., 0., 0.]), dtype('float64'), numpy.ndarray)

In [3]:
array = np.zeros(2, dtype = 'str')
array                                         #in string data type it is not give a zeros 

array(['', ''], dtype='<U1')

In [4]:
array = np.zeros(2, dtype = 'int')
array

array([0, 0])

In [5]:
arr = np.zeros((2,2), dtype = 'int')
arr

array([[0, 0],
       [0, 0]])

In [6]:
arr = np.zeros([2,2], dtype = 'int')
arr

array([[0, 0],
       [0, 0]])

In [7]:
arra =np.zeros((2,6),dtype = "int")
arra

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [8]:
arr = np.zeros([5,5],dtype = int)
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [9]:
arr = np.zeros([5,5])
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## 2. ones()

In [ ]:
### It will create an array where all the elements will be one.

In [10]:
arr = np.ones((5,5), dtype='int')
arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
arr = np.ones((2,2),dtype = "str")
arr

array([['1', '1'],
       ['1', '1']], dtype='<U1')

In [12]:
arr1 = np.ones((3,4))
arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
arr1 = np.ones((3,4),dtype = int)
arr1

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

## 3. arange()

In [ ]:
# range (0,10) == 0,1,2,3....9
# range(2,10,2) == 2,4,6,8
# arange(satrt_index,end_index,step_size)

In [14]:
arr = np.arange(1,10) #(1,2,3,....9)(n,n-1)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr = np.arange(1,10,2)  # 1,3,5,
arr

array([1, 3, 5, 7, 9])

In [16]:
arr = np.arange(1,10).reshape(3,3)    # 9 (9*1,1*9,3*3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr = np.arange(1,10).reshape(1,9)    # 9 (9*1,1*9)
arr

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

## 4. linspace()

In [ ]:
linspace(start, end, num = digit, retstep= True)

In [3]:
import numpy as np
array = np.linspace(0,50) # by default it give us 50 nums
array 
# print(len(array))   

array([ 0.        ,  1.02040816,  2.04081633,  3.06122449,  4.08163265,
        5.10204082,  6.12244898,  7.14285714,  8.16326531,  9.18367347,
       10.20408163, 11.2244898 , 12.24489796, 13.26530612, 14.28571429,
       15.30612245, 16.32653061, 17.34693878, 18.36734694, 19.3877551 ,
       20.40816327, 21.42857143, 22.44897959, 23.46938776, 24.48979592,
       25.51020408, 26.53061224, 27.55102041, 28.57142857, 29.59183673,
       30.6122449 , 31.63265306, 32.65306122, 33.67346939, 34.69387755,
       35.71428571, 36.73469388, 37.75510204, 38.7755102 , 39.79591837,
       40.81632653, 41.83673469, 42.85714286, 43.87755102, 44.89795918,
       45.91836735, 46.93877551, 47.95918367, 48.97959184, 50.        ])

In [21]:
array = np.linspace(1,10)
array

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [22]:
9.44897959- 9.26530612

0.18367347000000045

In [23]:
6.69387755-6.51020408

0.18367346999999956

In [5]:
array = np.linspace(0,20, num=21,retstep=True) 
array
#len(array)

(array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19., 20.]),
 1.0)

In [31]:
array = np.linspace(2,30, num=20, retstep=True) 
array

(array([ 2.        ,  3.47368421,  4.94736842,  6.42105263,  7.89473684,
         9.36842105, 10.84210526, 12.31578947, 13.78947368, 15.26315789,
        16.73684211, 18.21052632, 19.68421053, 21.15789474, 22.63157895,
        24.10526316, 25.57894737, 27.05263158, 28.52631579, 30.        ]),
 1.4736842105263157)

In [33]:
array = np.linspace(0,10,num = 6,retstep=True)
array

(array([ 0.,  2.,  4.,  6.,  8., 10.]), 2.0)

In [34]:
array = np.linspace(0,20, retstep=True) # by default it give us 50 nums
array,type(array)

((array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
          2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
          4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
          6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
          8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
         10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
         12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
         14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
         16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
         18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ]),
  0.40816326530612246),
 tuple)

## 5. eye()    

In [ ]:
import numpy as np

In [35]:
arr = np.eye(2,2, dtype= 'int')
arr

array([[1, 0],
       [0, 1]])

In [36]:
arr = np.eye(5, dtype= 'int')
arr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [37]:
arr = np.eye(3,5, dtype= 'int')
arr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [38]:
arr = np.eye(3,5, dtype= 'int', k= 1)
arr

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [39]:
arr = np.eye(3,5, dtype= 'int', k= 2)
arr

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [40]:
arr = np.eye(3,5, dtype= 'int', k= 3)
arr

array([[0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

In [42]:
arr = np.eye([3,5], dtype= 'int', k= 3)
arr

TypeError: 'list' object cannot be interpreted as an integer

## 6. identity()   It is always 2x2 or 3x3 

In [43]:
array = np.identity(5, dtype='int')
array

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [44]:
array = np.identity(3, dtype='int')
array

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [45]:
array = np.identity(3,5, dtype='int')
array

TypeError: identity() got multiple values for argument 'dtype'

## 7. random()

In [ ]:
There are multiple function inside random function.
rand()
random()
randint()
randn()
ranf()

### 7.1 random.rand()

In [ ]:
It will always generate the random nos. from range 0 to 1.

In [47]:
arr1 = np.random.rand(8)
print(len(arr1))
arr1

8


array([0.7933472 , 0.6609428 , 0.94280721, 0.46669339, 0.6332099 ,
       0.27301169, 0.86375364, 0.8458903 ])

In [48]:
np.random.rand(4)

array([0.03425261, 0.32366737, 0.82944927, 0.31221573])

In [49]:
np.random.rand(5)

array([0.44115835, 0.56531961, 0.12499748, 0.97313036, 0.94858485])

In [50]:
arry1 = np.random.rand(50)
arry1

array([0.71133579, 0.49799675, 0.84079838, 0.17794837, 0.08950366,
       0.85642234, 0.68809984, 0.70728084, 0.6993602 , 0.08128247,
       0.43129069, 0.69935914, 0.21571298, 0.1507489 , 0.64450734,
       0.56965429, 0.45770257, 0.62533019, 0.33489236, 0.88222776,
       0.38484075, 0.82452837, 0.85472672, 0.91205951, 0.73838603,
       0.72742336, 0.50533382, 0.36404474, 0.18191013, 0.10394268,
       0.01101445, 0.77386069, 0.34883366, 0.94187855, 0.45078169,
       0.0860358 , 0.15699243, 0.39794971, 0.51524311, 0.74494688,
       0.29299891, 0.60341244, 0.47989496, 0.3490472 , 0.97492665,
       0.15403504, 0.16923543, 0.16054212, 0.78762572, 0.32152598])

In [51]:
np.random.rand(10)

array([0.78765172, 0.21572048, 0.16967834, 0.53454362, 0.69594343,
       0.0126124 , 0.29711707, 0.17372137, 0.06116355, 0.97944352])

In [52]:
np.random.rand(2,4)

array([[0.32511392, 0.66199483, 0.5382844 , 0.50456977],
       [0.36163213, 0.36357229, 0.29655005, 0.24555885]])

In [53]:
np.random.rand(2,5)

array([[0.90055437, 0.96140018, 0.33059938, 0.48399581, 0.3627772 ],
       [0.36262153, 0.06363565, 0.50434922, 0.6780567 , 0.87770315]])

In [54]:
np.random.rand(5,5)

array([[0.41309314, 0.3122682 , 0.48133297, 0.18361554, 0.64135666],
       [0.02153427, 0.72013106, 0.40003669, 0.57874823, 0.07856609],
       [0.71465565, 0.92857305, 0.48698514, 0.14717328, 0.41475026],
       [0.30157711, 0.09994507, 0.79405018, 0.35087206, 0.1487964 ],
       [0.56232265, 0.64594828, 0.98797393, 0.78595033, 0.69235404]])

## 7.2 random.random()        

In [ ]:
It will always generate the random nos. from range 0 to 1.

In [55]:
np.random.random(40)

array([9.88727717e-01, 2.64471121e-01, 8.54226191e-02, 1.83594119e-02,
       8.69527965e-01, 7.66859145e-01, 7.55157436e-01, 7.70456605e-01,
       4.24230839e-01, 2.82087964e-02, 4.62659011e-01, 4.45014612e-01,
       1.31333926e-01, 3.53439222e-01, 3.73294096e-01, 4.94776670e-02,
       9.34931380e-01, 9.71292720e-01, 2.75686329e-02, 9.84936107e-04,
       2.36995745e-01, 3.25820423e-01, 8.03473919e-01, 1.23917285e-01,
       4.19454222e-01, 2.99464172e-01, 6.56116287e-01, 6.70733018e-01,
       4.51636212e-01, 1.40438134e-01, 9.43837043e-01, 2.13391691e-01,
       4.98611008e-01, 3.48965095e-01, 3.94324840e-01, 4.10124088e-01,
       2.54331157e-01, 8.36663065e-02, 9.71421812e-01, 6.58257938e-01])

In [56]:
np.random.random(2,2)

TypeError: random() takes at most 1 positional argument (2 given)

In [57]:
np.random.random((2,2))

array([[0.88848048, 0.71133577],
       [0.4166907 , 0.70311481]])

### 7.3 random.randint()    it gives us integer numbers 

In [60]:
np.random.randint(1,20)  # by default it is giving a only one random number

7

In [62]:
np.random.randint(1,20,10)

array([ 2, 15, 17, 17, 13,  7,  4,  1, 11,  9])

In [63]:
np.random.randint(1,20, size=20, dtype ='float')

TypeError: Unsupported dtype dtype('float64') for randint

In [65]:
np.random.randint(1,20, size=20,)

array([10, 10,  2,  3, 19, 15,  9,  1, 19,  4, 15,  2, 17, 13, 10, 13, 16,
        2, 15, 19])

### 7.4 random.randn()

In [ ]:
It will retuen the normally distributed numbers around (0,0) co-ordinates.

In [ ]:
-3,-2,-,1,0,1,2,3

In [66]:
np.random.randn(2) # -2,-1,0,1,2

array([-0.46727375, -1.28250002])

In [67]:
np.random.randn(2,2)

array([[-1.56955119,  0.52571753],
       [ 1.33604478,  0.53942924]])

In [68]:
np.random.randn(2,5)

array([[ 0.77265805, -1.10753176,  1.92404986,  0.45472919,  0.18321138],
       [-0.09830133, -1.04625347,  0.85985437,  0.51055314, -1.39945843]])

### 5. random.ranf()    range(0-1)

In [69]:
np.random.ranf(2)

array([0.27367494, 0.35937085])

In [70]:
np.random.ranf(5)

array([0.17171896, 0.69046389, 0.84577335, 0.25110796, 0.57349599])

In [71]:
np.random.ranf((5,2))

array([[0.4055374 , 0.77122956],
       [0.84119997, 0.02468755],
       [0.49059117, 0.64652989],
       [0.33201611, 0.68066503],
       [0.78218174, 0.04460082]])

In [72]:
np.random.ranf(5)

array([0.17114607, 0.80541007, 0.66482181, 0.47502525, 0.69100178])

In [ ]:
1) zeros()   it will create a zeros array
2) ones()   it will craete a ones array
3) arange()  it gives us a range of specific number  np.arange(start_index,end_index,step_size)
4) linspace()  it gives equally distributed numbers with the specific range 

np.linspace(start_index,end_index,num = int ,retstep = True)
num = how many numbers we want to dispaly with equal spacing

5) eye()  it gives a matrix with all digonals are one

6) identity()  it gives us identity matrics 
7) random
a) rand()      (0-1)
b) random()    (0-1)
c) randint()    random int
d) ranf()       (0-1)
e) randn()       normally distributed numbers

## sort()

np.sort()

In [ ]:
array = np.random.randint(1,20, 10)
array

In [ ]:
np.sort(array)

In [ ]:
np.sort(array)[::-1]

## insert

In [ ]:
It insert an element inside array at a specific position.

In [ ]:
import numpy as np

In [ ]:
arr =  np.array([1,4,6,8])
arr 

In [ ]:
np.insert(arr,2,30)

In [ ]:
arra1= np.insert(arr, 1, 20)
# np.insert(array, position, element)
arra1

In [ ]:
arr2 = np.array([1,3,5])
arr2

In [ ]:
arr

In [ ]:
np.insert(arr, 1, arr2) # 1,1, 3, 5,4, 6, 8

In [ ]:
arr1 = np.array([1,2,3])
arra2 = np.array([4,5,6])
np.insert(arr1,3,arra2)

In [ ]:
arr3 = arr1+arra2  #(1+4=5),(2+5=7)(3+6=9)
arr3

## append

In [ ]:
arr

In [ ]:
arr2

In [ ]:
np.append(arr, 10)

In [ ]:
np.append(arr, arr2)

In [ ]:
np.append(arr, (10,20))

In [ ]:
arr3 = np.array([[1,2],[3,4]])
arr3,arr3.ndim

In [ ]:
arr4 = np.array([[5,6]])
arr4,arr4.ndim

In [ ]:
arr5 = np.append(arr3,arr4) 
arr5,arr5.ndim

In [ ]:
np.append(arr3,arr4, axis=0)    # axis = 0 rows  

In [ ]:
arr3

In [ ]:
arr5 = np.array([[8,7],[3,4]])
arr5

In [ ]:
np.append(arr3,arr5, axis=1)     

In [ ]:
np.append(arr3,arr5, axis=0)

In [ ]:
arr5 =  np.array([[7],[8]])
arr5

In [ ]:
arr3

In [ ]:
np.append(arr3,arr5, axis=1)

In [ ]:
np.append(arr3,arr5, axis=0)

In [ ]:
arr2 = np.arange(1,21)
arr2

## concatenate()

concatenate the arrays along with the axis

In [6]:
array1 = np.array([1,2,3])
array2 = np.concatenate([array1, [10]])
array2

array([ 1,  2,  3, 10])

In [ ]:
array2 = np.array([5,6,7,8])
array3 = np.array([9,10,11])
np.concatenate([array1,array2, array3])

In [ ]:
np.concatenate([array1,array3, array2])

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.array([7,8,9])
np.concatenate([arr1,arr2,arr3])

In [ ]:
np.concatenate([arr1,arr3,arr2])

In [ ]:
arr3

In [ ]:
arr4

In [ ]:
np.append(arr3,arr4)

In [ ]:
np.concatenate([arr3,arr4])

In [ ]:
np.concatenate([arr3,arr5], axis=1)

In [ ]:
axis = 0 >> it is about concatinating row wise
axis = 1 >> is about concatinating column wise

In [ ]:
for i in arr:
    print(i)

In [ ]:
for i , val in np.ndenumerate(arr):
    print(i, val)

In [ ]:
arr3

In [ ]:
for i , val in np.ndenumerate(arr3):
    print(i, val)

In [ ]:
for i in np.nditer(arr):
    print(i)

In [ ]:
for i in np.nditer(arr3):
    print(i)
    

## Ceil

In [ ]:
-2.1 >> -2
-2.5 >> -2
2.6 >> 3
it returns round figure of closest maximum value.

In [ ]:
np.ceil(2.1)

In [9]:
np.ceil(2.5)

3.0

In [ ]:
np.ceil(-2.1)

In [ ]:
np.ceil(3.4)

In [ ]:
np.ceil(-2.8)

## floor

In [ ]:
it reduces the number to its closest minimum whole number.

In [ ]:
np.floor(2.6)

In [ ]:
np.floor(2.9)

In [ ]:
np.floor(-2.1)

## around()

In [13]:
np.around(2.6)

3.0

In [ ]:
np.around(2.1)

In [ ]:
np.around(2.5)

In [ ]:
np.around([4.2,3.8,1.1])


In [ ]:
np.round([4.2,3.8,1.1])

## copy

In [ ]:
arr = np.array([1,2,3,4])
arr

In [ ]:
arr2 = arr.copy()
arr2

In [ ]:
arr3 = np.array([[1,2],[3,4]])
arr3

In [ ]:
arr4 = arr3.copy() # it works like deep copy
arr4

## where

In [ ]:
np.where

In [14]:
arr = np.array([4,2,3,7])
np.where(arr==2)

(array([1], dtype=int64),)

In [15]:
arr = np.array([4,2,3,7,4,5,4])
np.where(arr==4)

(array([0, 4, 6], dtype=int64),)

In [ ]:
arr = np.array([4,2,3,7,4,5,4])
np.where(arr==4, 20 ,arr)

## size

In [ ]:
arr

In [ ]:
np.size(arr)

In [16]:
arr2 = np.array([4,5,2,11,7,8,1])
arr2
np.size(arr2)
len(arr2)

7

## argmax it gives indexing of the maximum number 

In [ ]:
arr2

In [ ]:
np.argmax(arr2)

In [ ]:
arr3 = np.array([90,5,7,8])
np.argmax(arr3)

## argmin   

In [ ]:
arr2

In [ ]:
np.argmin(arr2)

## argsort

In [ ]:
arr2

In [ ]:
1,2,4,5,7,8,11
6,2,0,1,4,5,3

In [ ]:
np.argsort(arr2) # 1=6,2=2, 4=0, 5=1,7=4,8=5,11=3

In [ ]:
np.sort(arr2)

In [ ]:
np.sum(arr2)

In [ ]:
np.mean(arr2)                    #avg

In [ ]:
np.median(arr2)     #1,2,3,4,5,

In [ ]:
np.std(arr2) # standard deviation = summation(a -a.mean())**2

In [ ]:
np.square(arr2)

In [ ]:
np.power(arr2, 2)

In [ ]:
np.power(arr2, 4)

In [ ]:
arr2

In [ ]:
arr2 + 5

In [ ]:
arr2 -1

In [ ]:
arr2*2

In [ ]:
arr2/2

In [ ]:
arr2%2

In [ ]:
arr

In [ ]:
arr2

In [ ]:
arr + arr2

In [ ]:
arr3 = np.array([1,7,8,6])
arr3

In [ ]:
arr3 + arr2 # shape of array should be same.

In [ ]:
np.add(arr,arr2)

In [ ]:
np.multiply(arr, arr2)

In [ ]:
np.subtract(arr, arr2)

In [ ]:
np.multiply(arr, arr2)

In [ ]:
np.divide(arr,arr2)