In [ ]:
sort()
insert()  == np.insert(arry,position,element)
append()  == add array inside a array
concate()  == it is use to join the two array 
ceil() == it gives closest maximum value
floor == it gives closest minimum value
around == round up the value
copy == 
where == 
size 
sum
mean
median
mod
std
argmax
argmin
argsort
power
square
+
-
*
/
//

## Matrix Dot Product

In [3]:
import numpy as np

In [4]:
arr1 = np.array([[1,2],[3,4]])
arr1

array([[1, 2],
       [3, 4]])

In [5]:
arr2 = np.array([[5,6],[7,8]])
arr2

array([[5, 6],
       [7, 8]])

In [ ]:
2x(2) , 2x(2) >> 2x2
3x2 , 2x2 >> 3x2
2x4 , 4x3 >> 2x3
3x2 , 2x3 >> 3x3

In [ ]:
arr1, arr2

2x2 , 2x2 >> 2x2
[1 2
 3 4]      
  [5  6
  7  8]
1x5 + 2x7 = 19
1x6 + 2x8 = 22

3x5 +4x7 = 43
3x6 +4x8 = 50

In [6]:
np.dot(arr1,arr2)

array([[19, 22],
       [43, 50]])

## Logarithmic Functions

In [7]:
np.log(np.exp(1)) # Natural log. is a log e to the base any number.

1.0

In [8]:
np.exp(1)      

2.718281828459045

In [9]:
np.log(2.718281828459045)

1.0

In [10]:
np.exp(10)

22026.465794806718

In [11]:
np.log(22026.465794806718)

10.0

In [12]:
np.log10(1000) # 10**3

3.0

In [13]:
np.log10(100)

2.0

In [14]:
np.log10(2)

0.3010299956639812

In [15]:
np.log2(1)

0.0

In [16]:
np.log2(256)

8.0

## Numpy Trignometry

In [ ]:
sin = opp/hyp                    pi = 180  , 180/2 = 90  = pi/2 ,180/4 = 45 =  pi/4,
cos = adj/hyp
tan = sin/cos = opp/adj
cosec = 1/sin = hyp/opp
sec = 1/cos = hyp/adj
cot = 1/tan = adj/opp

In [17]:
np.pi

3.141592653589793

In [18]:
sin_45 = np.sin(np.pi/4)   #pi/4 == 45
sin_45

0.7071067811865476

In [19]:
sin_30 = np.sin(np.pi/6)   # pi/6
sin_30

0.49999999999999994

In [20]:
sin_60 = np.sin(np.pi/3)  # pi/6 = 60
sin_60

0.8660254037844386

In [21]:
sin_90 = np.sin(np.pi/2)
sin_90

1.0

In [22]:
cos_30 = np.cos(np.pi/6)
cos_30

0.8660254037844387

In [23]:
tan_45 = np.tan(np.pi/4)
tan_45

0.9999999999999999

## Degree to radian

In [24]:
angle = np.deg2rad(60)
angle

1.0471975511965976

In [25]:
ang = np.deg2rad(30)
ang

0.5235987755982988

In [26]:
angles = np.deg2rad([0,30,45,60,90])
angles

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [27]:
np.sin(angles)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

## Radian to Degree

In [28]:
angles = np.deg2rad([0,30,45,60,90])
angles

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [29]:
angles_rd = np.array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])
degrees = np.rad2deg(angles_rd)
degrees

array([ 0.        , 30.00000025, 44.99999981, 59.99999993, 90.00000018])